# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-20 15:39
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import embed_video.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=250, verbose_name=b'Article Title')),
                ('article_date', models.DateTimeField(verbose_name=b'Release date')),
                ('article_video', embed_video.fields.EmbedVideoField(blank=True, help_text=b'URL video', null=True, verbose_name=b'Video')),
                ('video_published', models.BooleanField(default=b'')),
                ('slug', models.CharField(blank=True, max_length=250, verbose_name=b'Url')),
                ('slogan', models.CharField(max_length=250, verbose_name=b'Article Slogan')),
                ('short_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name=b'Short text')),
                ('full_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name=b'Full text')),
                ('published', models.BooleanField(verbose_name=b'Published')),
                ('published_main', models.BooleanField(default=b'', verbose_name=b'Published on main page')),
                ('ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name=b'Ordering')),
            ],
            options={
                'ordering': ['ordering'],
                'db_table': 'articles',
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=b'', max_length=250, unique=True, verbose_name=b'Name Category')),
                ('published', models.BooleanField(default=b'', verbose_name=b'Published')),
                ('ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name=b'Ordering')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='article.Category', verbose_name=b'Parent class')),
            ],
            options={
                'ordering': ('tree_id', 'level'),
                'db_table': 'category',
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=250, verbose_name=b'Url')),
                ('name', models.CharField(blank=True, default=b'', max_length=200, unique=True, verbose_name=b'Creator device')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='article.Creator', verbose_name=b'Parent class')),
            ],
            options={
                'ordering': ('tree_id', 'level'),
                'db_table': 'creators',
                'verbose_name': 'Creator',
                'verbose_name_plural': 'Creators',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name=b'Name')),
                ('slug', models.CharField(blank=True, max_length=250, verbose_name=b'Url')),
                ('published', models.BooleanField(verbose_name=b'Published')),
                ('ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name=b'Ordering')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Category', verbose_name=b'Category')),
            ],
            options={
                'ordering': ['ordering'],
                'db_table': 'menuItemsArticles',
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items for Articles',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name=b'Support Title')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, help_text=b'URL video', null=True, verbose_name=b'Video')),
                ('video_published', models.BooleanField(default=b'')),
                ('slug', models.CharField(blank=True, max_length=250, verbose_name=b'Url')),
                ('slogan', models.CharField(max_length=250, verbose_name=b'Support Slogan')),
                ('short_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name=b'Short text')),
                ('full_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name=b'Full text')),
                ('published', models.BooleanField(verbose_name=b'Published')),
                ('ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name=b'Ordering')),
                ('category', mptt.fields.TreeForeignKey(blank=True, default=b'', on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='article.Category', verbose_name=b'Categories')),
            ],
            options={
                'ordering': ['ordering'],
                'db_table': 'support',
                'verbose_name': 'Support',
                'verbose_name_plural': 'Supports',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, verbose_name=b'Tag Name')),
            ],
            options={
                'db_table': 'tags',
                'verbose_name': 'tags',
                'verbose_name_plural': 'tag',
            },
        ),
        migrations.AddField(
            model_name='support',
            name='tag',
            field=models.ManyToManyField(related_name='support_tags', related_query_name=b'support_tags', to='article.Tag', verbose_name=b'Tags'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_category',
            field=mptt.fields.TreeForeignKey(blank=True, default=b'', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='article.Category', verbose_name=b'Categories'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_creator',
            field=mptt.fields.TreeForeignKey(blank=True, default=b'', max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='article.Creator', verbose_name=b'Creator'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_tag',
            field=models.ManyToManyField(related_name='tags', related_query_name=b'tags', to='article.Tag', verbose_name=b'Tags'),
        ),
    ]
